  <img id="blank-dead-down-one" src="assets/img/blank/walking/tile012.png"/>
  <img id="blank-walking-down-one" src="assets/img/blank/walking/tile000.png"/>
  <img id="blank-walking-down-two" src="assets/img/blank/walking/tile001.png"/>
  <img id="blank-walking-down-three" src="assets/img/blank/walking/tile002.png"/>
  <img id="blank-walking-up-one" src="assets/img/blank/walking/tile003.png"/>
  <img id="blank-walking-up-two" src="assets/img/blank/walking/tile004.png"/>
  <img id="blank-walking-up-three" src="assets/img/blank/walking/tile005.png"/>
  <img id="blank-walking-left-one" src="assets/img/blank/walking/tile006.png"/>
  <img id="blank-walking-left-two" src="assets/img/blank/walking/tile007.png"/>
  <img id="blank-walking-left-three" src="assets/img/blank/walking/tile008.png"/>
  <img id="blank-walking-right-one" src="assets/img/blank/walking/tile009.png"/>
  <img id="blank-walking-right-two" src="assets/img/blank/walking/tile010.png"/>
  <img id="blank-walking-right-three" src="assets/img/blank/walking/tile011.png"/>
  <img id="blank-attacking-down-one" src="assets/img/blank/attacking/tile000.png"/>
  <img id="blank-attacking-down-two" src="assets/img/blank/attacking/tile001.png"/>
  <img id="blank-attacking-down-three" src="assets/img/blank/attacking/tile002.png"/>
  <img id="blank-attacking-up-one" src="assets/img/blank/attacking/tile003.png"/>
  <img id="blank-attacking-up-two" src="assets/img/blank/attacking/tile004.png"/>
  <img id="blank-attacking-up-three" src="assets/img/blank/attacking/tile005.png"/>
  <img id="blank-attacking-left-one" src="assets/img/blank/attacking/tile006.png"/>
  <img id="blank-attacking-left-two" src="assets/img/blank/attacking/tile007.png"/>
  <img id="blank-attacking-left-three" src="assets/img/blank/attacking/tile008.png"/>
  <img id="blank-attacking-right-one" src="assets/img/blank/attacking/tile009.png"/>
  <img id="blank-attacking-right-two" src="assets/img/blank/attacking/tile010.png"/>
  <img id="blank-attacking-right-three" src="assets/img/blank/attacking/tile011.png"/>
  <img id="blank-sleeping-down-one" src="assets/img/blank/sleeping/tile000.png"/>
  <img id="blank-sleeping-down-two" src="assets/img/blank/sleeping/tile001.png"/>
  <img id="blank-sleeping-down-three" src="assets/img/blank/sleeping/tile002.png"/>
  <img id="blank-sleeping-up-one" src="assets/img/blank/sleeping/tile000.png"/>
  <img id="blank-sleeping-up-two" src="assets/img/blank/sleeping/tile001.png"/>
  <img id="blank-sleeping-up-three" src="assets/img/blank/sleeping/tile002.png"/>
  <img id="blank-sleeping-left-one" src="assets/img/blank/sleeping/tile000.png"/>
  <img id="blank-sleeping-left-two" src="assets/img/blank/sleeping/tile001.png"/>
  <img id="blank-sleeping-left-three" src="assets/img/blank/sleeping/tile002.png"/>
  <img id="blank-sleeping-right-one" src="assets/img/blank/sleeping/tile000.png"/>
  <img id="blank-sleeping-right-two" src="assets/img/blank/sleeping/tile001.png"/>
  <img id="blank-sleeping-right-three" src="assets/img/blank/sleeping/tile002.png"/>
  



////////////////////////////////////////////////////////////////////////////////////////////

//evolution
if(self.name === "machop"){if(self.level > 27){self.name = "machoke";}}if(self.name === "machop" || self.name === "machoke"){if(self.level > 39){self.name = "machamp";}}
//type
if(self.name === "machop" ||self.name === "machoke" || self.name === "machamp"){self.type = "fighting";}

if(self.name === "venonat" ||self.name === "butterfree"){self.type = "poison";}





